name: Max Martinez
favicon: null
layout_spectrum: 0.9997180916834623
typography_spectrum: 0.9648252238985151
title: Max Martinez
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#febe10'
    - '#00529f'
    - '#ffffff'
    - '#ee324e'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
