typography_spectrum: 0.344
color:
  brandColors:
    - '#febe10'
    - '#00529f'
    - '#ffffff'
    - '#ee324e'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.56929
analytics:
  google: null
  facebook: null
  twitter: null
name: Max Martinez
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Miami Legacy
    id: 66a25083-e9f5-4cc1-843b-788d507a66f7
    type: content
favicon: null
title: Max Martinez
description: A creator with an athlete's heart.
purpose: []
