name: Max Martinez
favicon: null
layout_spectrum: 0.56929
typography_spectrum: 0.25398
title: Max Martinez
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#febe10'
    - '#00529f'
    - '#ffffff'
    - '#ee324e'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
